/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_com_ITypeInfo_Native */

#ifndef _Included_jp_hishidama_win32_com_ITypeInfo_Native
#define _Included_jp_hishidama_win32_com_ITypeInfo_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_com_ITypeInfo_Native
 * Method:    GetIDsOfNames
 * Signature: (J[Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_jp_hishidama_win32_com_ITypeInfo_00024Native_GetIDsOfNames
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     jp_hishidama_win32_com_ITypeInfo_Native
 * Method:    GetDocumentation
 * Signature: (JJ[Ljava/lang/String;[Ljava/lang/String;[I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_com_ITypeInfo_00024Native_GetDocumentation
  (JNIEnv *, jclass, jlong, jlong, jobjectArray, jobjectArray, jintArray, jobjectArray);

/*
 * Class:     jp_hishidama_win32_com_ITypeInfo_Native
 * Method:    GetMops
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_com_ITypeInfo_00024Native_GetMops
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
