/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLBRElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLBRElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLBRElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLBRElement_Native
 * Method:    put_clear
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLBRElement_00024Native_put_1clear
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLBRElement_Native
 * Method:    get_clear
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLBRElement_00024Native_get_1clear
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
