/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLButtonElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    get_type
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_get_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    put_value
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_put_1value
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    get_value
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_get_1value
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    put_name
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_put_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    get_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_get_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    put_status
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_put_1status
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    get_status
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_get_1status
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    put_disabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_put_1disabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    get_disabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_get_1disabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    get_form
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLFormElement;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_get_1form
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLButtonElement_Native
 * Method:    createTextRange
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLTxtRange;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLButtonElement_00024Native_createTextRange
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
