/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLCommentElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    put_text
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_put_1text
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    get_text
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_get_1text
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    put_atomic
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_put_1atomic
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    get_atomic
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_get_1atomic
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    put_data
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_put_1data
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    get_data
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_get_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    get_length
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_get_1length
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    substringData
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_substringData
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    appendData
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_appendData
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    insertData
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_insertData
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    deleteData
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_deleteData
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLCommentElement_Native
 * Method:    replaceData
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLCommentElement_00024Native_replaceData
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
