/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    setAttribute
 * Signature: (JLjava/lang/String;Ljp/hishidama/win32/com/Variant;I)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_setAttribute
  (JNIEnv *, jclass, jlong, jstring, jobject, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    getAttribute
 * Signature: (JLjava/lang/String;I)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_getAttribute
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    removeAttribute
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_removeAttribute
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_className
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1className
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_className
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1className
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_id
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1id
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_id
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1id
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_tagName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1tagName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_parentElement
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLElement;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1parentElement
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_title
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1title
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_document
 * Signature: (J)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1document
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_title
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1title
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_language
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1language
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_language
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1language
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_lang
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1lang
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_lang
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1lang
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_offsetLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1offsetLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_offsetTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1offsetTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_offsetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1offsetWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_offsetHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1offsetHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_offsetParent
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLElement;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1offsetParent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_innerHTML
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1innerHTML
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_innerHTML
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1innerHTML
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_innerText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1innerText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_innerText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1innerText
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_outerHTML
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1outerHTML
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_outerHTML
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1outerHTML
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_outerText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1outerText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_outerText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1outerText
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_parentTextEdit
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLElement;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1parentTextEdit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_isTextEdit
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1isTextEdit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    click
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_click
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_children
 * Signature: (J)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1children
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_all
 * Signature: (J)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1all
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_scopeName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1scopeName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    focus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_focus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_clientLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1clientLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_clientTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1clientTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_clientWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1clientWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_clientHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1clientHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_dir
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1dir
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_dir
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1dir
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_scrollLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1scrollLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_scrollLeft
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1scrollLeft
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_scrollTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1scrollTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_scrollTop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1scrollTop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_scrollWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1scrollWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_scrollHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1scrollHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_tagUrn
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1tagUrn
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_tagUrn
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1tagUrn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    getElementsByTagName
 * Signature: (JLjava/lang/String;)Ljp/hishidama/win32/mshtml/IHTMLElementCollection;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_getElementsByTagName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_isMultiLine
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1isMultiLine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_canHaveHTML
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1canHaveHTML
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_inflateBlock
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1inflateBlock
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_inflateBlock
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1inflateBlock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    setActive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_setActive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_contentEditable
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1contentEditable
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_contentEditable
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1contentEditable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_isContentEditable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1isContentEditable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_hideFocus
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1hideFocus
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_hideFocus
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1hideFocus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    put_disabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_put_1disabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_disabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1disabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_isDisabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1isDisabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    dragDrop
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_dragDrop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    get_glyphMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_get_1glyphMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLElement_Native
 * Method:    normalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLElement_00024Native_normalize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
