/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLFramesCollection_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLFramesCollection_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLFramesCollection_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFramesCollection_Native
 * Method:    item
 * Signature: (JLjp/hishidama/win32/com/Variant;)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFramesCollection_00024Native_item
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFramesCollection_Native
 * Method:    get_length
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFramesCollection_00024Native_get_1length
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
