/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLLIElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLLIElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLLIElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLLIElement_Native
 * Method:    put_type
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLLIElement_00024Native_put_1type
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLLIElement_Native
 * Method:    get_type
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLLIElement_00024Native_get_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLLIElement_Native
 * Method:    put_value
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLLIElement_00024Native_put_1value
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLLIElement_Native
 * Method:    get_value
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLLIElement_00024Native_get_1value
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
