/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLPhraseElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLPhraseElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLPhraseElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLPhraseElement_Native
 * Method:    put_cite
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLPhraseElement_00024Native_put_1cite
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLPhraseElement_Native
 * Method:    get_cite
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLPhraseElement_00024Native_get_1cite
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLPhraseElement_Native
 * Method:    put_dateTime
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLPhraseElement_00024Native_put_1dateTime
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLPhraseElement_Native
 * Method:    get_dateTime
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLPhraseElement_00024Native_get_1dateTime
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
