/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_bgColor
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1bgColor
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_bgColor
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1bgColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_scrollDelay
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1scrollDelay
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_scrollDelay
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1scrollDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_direction
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1direction
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_direction
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1direction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_behavior
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1behavior
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_behavior
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1behavior
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_scrollAmount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1scrollAmount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_scrollAmount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1scrollAmount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_loop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1loop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_loop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1loop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_vspace
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1vspace
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_vspace
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1vspace
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_hspace
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1hspace
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_hspace
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1hspace
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_width
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1width
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_width
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_height
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1height
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_height
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1height
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    put_trueSpeed
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_put_1trueSpeed
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    get_trueSpeed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_get_1trueSpeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    Start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_Start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMarqueeElement_Native
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMarqueeElement_00024Native_stop
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
