/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLOptionElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    put_selected
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_put_1selected
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    get_selected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_get_1selected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    put_value
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_put_1value
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    get_value
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_get_1value
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    put_defaultSelected
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_put_1defaultSelected
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    get_defaultSelected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_get_1defaultSelected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    put_index
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_put_1index
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    get_index
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_get_1index
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    put_text
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_put_1text
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    get_text
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_get_1text
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    get_form
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLFormElement;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_get_1form
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    put_label
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_put_1label
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    get_label
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_get_1label
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLOptionElement_Native
 * Method:    create
 * Signature: (JLjava/lang/String;Ljava/lang/String;ZZ)Ljp/hishidama/win32/mshtml/IHTMLOptionElement;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLOptionElement_00024Native_create
  (JNIEnv *, jclass, jlong, jstring, jstring, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
