/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLMapElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLMapElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLMapElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMapElement_Native
 * Method:    get_areas
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLAreasCollection;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMapElement_00024Native_get_1areas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMapElement_Native
 * Method:    put_name
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMapElement_00024Native_put_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLMapElement_Native
 * Method:    get_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLMapElement_00024Native_get_1name
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
