/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLWindow_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLWindow_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLWindow_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_frames
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLFramesCollection;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1frames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    put_defaultStatus
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_put_1defaultStatus
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_defaultStatus
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1defaultStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    put_status
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_put_1status
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_status
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1status
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    alert
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_alert
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    confirm
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_confirm
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    prompt
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_prompt
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_location
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLLocation;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1location
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    put_opener
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_put_1opener
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_opener
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1opener
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    put_name
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_put_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_parent
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLWindow;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1parent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    open
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Ljp/hishidama/win32/mshtml/IHTMLWindow;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_open
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_self
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLWindow;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1self
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_top
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLWindow;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1top
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_window
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLWindow;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1window
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    navigate
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_navigate
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_document
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLDocument;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1document
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get__newEnum
 * Signature: (J)Ljp/hishidama/win32/com/IUnknown;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1_1newEnum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    focus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_focus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_closed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1closed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    blur
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_blur
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    scroll
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_scroll
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    execScript
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_execScript
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    scrollBy
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_scrollBy
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    scrollTo
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_scrollTo
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    moveTo
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_moveTo
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    moveBy
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_moveBy
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    resizeTo
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_resizeTo
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    resizeBy
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_resizeBy
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_external
 * Signature: (J)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1external
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_screenLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1screenLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    get_screenTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_get_1screenTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLWindow_Native
 * Method:    print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLWindow_00024Native_print
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
