/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLTextContainer_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLTextContainer_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLTextContainer_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTextContainer_Native
 * Method:    createControlRange
 * Signature: (J)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTextContainer_00024Native_createControlRange
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTextContainer_Native
 * Method:    get_scrollHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTextContainer_00024Native_get_1scrollHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTextContainer_Native
 * Method:    get_scrollWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTextContainer_00024Native_get_1scrollWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTextContainer_Native
 * Method:    put_scrollTop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTextContainer_00024Native_put_1scrollTop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTextContainer_Native
 * Method:    get_scrollTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTextContainer_00024Native_get_1scrollTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTextContainer_Native
 * Method:    put_scrollLeft
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTextContainer_00024Native_put_1scrollLeft
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTextContainer_Native
 * Method:    get_scrollLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTextContainer_00024Native_get_1scrollLeft
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
