/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_api_ObjBase */

#ifndef _Included_jp_hishidama_win32_api_ObjBase
#define _Included_jp_hishidama_win32_api_ObjBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_api_ObjBase
 * Method:    CoInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_ObjBase_CoInitialize
  (JNIEnv *, jclass);

/*
 * Class:     jp_hishidama_win32_api_ObjBase
 * Method:    CoInitializeEx
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_ObjBase_CoInitializeEx
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_hishidama_win32_api_ObjBase
 * Method:    CoUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_api_ObjBase_CoUninitialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
