/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_api_WinUser */

#ifndef _Included_jp_hishidama_win32_api_WinUser
#define _Included_jp_hishidama_win32_api_WinUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SendMessage
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_SendMessage__JIII
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SendMessage
 * Signature: (JIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_SendMessage__JIILjava_lang_String_2
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SendMessage
 * Signature: (JII[B)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_SendMessage__JII_3B
  (JNIEnv *, jclass, jlong, jint, jint, jbyteArray);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    PostMessage
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_PostMessage
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    IsWindow
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_IsWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    IsChild
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_IsChild
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    ShowWindow
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_ShowWindow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    MoveWindow
 * Signature: (JIIIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_MoveWindow
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jboolean);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SetWindowPos
 * Signature: (JJIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_SetWindowPos
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    IsWindowVisible
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_IsWindowVisible
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    IsIconic
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_IsIconic
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    IsZoomed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_IsZoomed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetDlgItem
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetDlgItem
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SetDlgItemInt
 * Signature: (JIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_SetDlgItemInt
  (JNIEnv *, jclass, jlong, jint, jint, jboolean);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetDlgItemInt
 * Signature: (JI[ZZ)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_GetDlgItemInt
  (JNIEnv *, jclass, jlong, jint, jbooleanArray, jboolean);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SetDlgItemText
 * Signature: (JILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_SetDlgItemText
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetDlgItemText
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_api_WinUser_GetDlgItemText
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    CheckDlgButton
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_CheckDlgButton
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    CheckRadioButton
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_CheckRadioButton
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    IsDlgButtonChecked
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_IsDlgButtonChecked
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetNextDlgGroupItem
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetNextDlgGroupItem
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetNextDlgTabItem
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetNextDlgTabItem
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetDlgCtrlID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_GetDlgCtrlID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SetFocus
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_SetFocus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetFocus
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetFocus
  (JNIEnv *, jclass);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SetActiveWindow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_SetActiveWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetActiveWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetActiveWindow
  (JNIEnv *, jclass);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    EnableWindow
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_EnableWindow
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    IsWindowEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_IsWindowEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SetForegroundWindow
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_SetForegroundWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetForegroundWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetForegroundWindow
  (JNIEnv *, jclass);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    ShowScrollBar
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_ShowScrollBar
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    EnableScrollBar
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_EnableScrollBar
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SetWindowText
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_SetWindowText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    getWindowText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_api_WinUser_getWindowText
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetWindowTextLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_GetWindowTextLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetClientRect
 * Signature: (JLjava/awt/Rectangle;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_GetClientRect
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetWindowRect
 * Signature: (JLjava/awt/Rectangle;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_GetWindowRect
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    MessageBox
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_MessageBox
  (JNIEnv *, jclass, jlong, jstring, jstring, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    ClientToScreen
 * Signature: (JLjava/awt/Point;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_ClientToScreen
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    ScreenToClient
 * Signature: (JLjava/awt/Point;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_ScreenToClient
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    WindowFromPoint
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_WindowFromPoint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    ChildWindowFromPoint
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_ChildWindowFromPoint
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    ChildWindowFromPointEx
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_ChildWindowFromPointEx
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetWindowLong
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_GetWindowLong
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SetWindowLong
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinUser_SetWindowLong
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetDesktopWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetDesktopWindow
  (JNIEnv *, jclass);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetParent
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetParent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    SetParent
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_SetParent
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    EnumChildWindows
 * Signature: (JLjava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_EnumChildWindows
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    EnumWindows
 * Signature: (Ljava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_api_WinUser_EnumWindows
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    FindWindow
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_FindWindow
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    getClassName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_api_WinUser_getClassName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetTopWindow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetTopWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetWindow
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetWindow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_api_WinUser
 * Method:    GetAncestor
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_api_WinUser_GetAncestor
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
