/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLTableSection_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLTableSection_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLTableSection_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    put_align
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_put_1align
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    get_align
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_get_1align
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    put_vAlign
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_put_1vAlign
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    get_vAlign
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_get_1vAlign
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    put_bgColor
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_put_1bgColor
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    get_bgColor
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_get_1bgColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    get_rows
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLElementCollection;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_get_1rows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    insertRow
 * Signature: (JI)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_insertRow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    deleteRow
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_deleteRow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    moveRow
 * Signature: (JII)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_moveRow
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    put_ch
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_put_1ch
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    get_ch
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_get_1ch
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    put_chOff
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_put_1chOff
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableSection_Native
 * Method:    get_chOff
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableSection_00024Native_get_1chOff
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
