/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLTableCell_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLTableCell_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLTableCell_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_rowSpan
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1rowSpan
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_rowSpan
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1rowSpan
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_colSpan
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1colSpan
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_colSpan
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1colSpan
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_align
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1align
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_align
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1align
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_vAlign
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1vAlign
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_vAlign
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1vAlign
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_bgColor
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1bgColor
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_bgColor
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1bgColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_noWrap
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1noWrap
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_noWrap
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1noWrap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_background
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1background
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_background
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1background
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_borderColor
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1borderColor
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_borderColor
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1borderColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_borderColorLight
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1borderColorLight
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_borderColorLight
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1borderColorLight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_borderColorDark
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1borderColorDark
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_borderColorDark
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1borderColorDark
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_width
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1width
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_width
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_height
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1height
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_height
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1height
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_cellIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1cellIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_abbr
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1abbr
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_abbr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1abbr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_axis
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1axis
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_axis
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1axis
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_ch
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1ch
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_ch
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1ch
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_chOff
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1chOff
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_chOff
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1chOff
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_headers
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1headers
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_headers
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1headers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    put_scope
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_put_1scope
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLTableCell_Native
 * Method:    get_scope
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLTableCell_00024Native_get_1scope
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
