/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_api_WinBase */

#ifndef _Included_jp_hishidama_win32_api_WinBase
#define _Included_jp_hishidama_win32_api_WinBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_api_WinBase
 * Method:    GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_api_WinBase_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     jp_hishidama_win32_api_WinBase
 * Method:    FormatMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_api_WinBase_FormatMessage
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
