/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_com_IDispatch_Native */

#ifndef _Included_jp_hishidama_win32_com_IDispatch_Native
#define _Included_jp_hishidama_win32_com_IDispatch_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_com_IDispatch_Native
 * Method:    GetTypeInfoCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_com_IDispatch_00024Native_GetTypeInfoCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_com_IDispatch_Native
 * Method:    GetTypeInfo
 * Signature: (JII)Ljp/hishidama/win32/com/ITypeInfo;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_com_IDispatch_00024Native_GetTypeInfo
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_hishidama_win32_com_IDispatch_Native
 * Method:    GetIDsOfNames
 * Signature: (JJ[Ljava/lang/String;I)[J
 */
JNIEXPORT jlongArray JNICALL Java_jp_hishidama_win32_com_IDispatch_00024Native_GetIDsOfNames
  (JNIEnv *, jclass, jlong, jlong, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
