/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_com_ComMgr */

#ifndef _Included_jp_hishidama_win32_com_ComMgr
#define _Included_jp_hishidama_win32_com_ComMgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_com_ComMgr
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_com_ComMgr_delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
