/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLFieldSetElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLFieldSetElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLFieldSetElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFieldSetElement_Native
 * Method:    put_align
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFieldSetElement_00024Native_put_1align
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFieldSetElement_Native
 * Method:    get_align
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFieldSetElement_00024Native_get_1align
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFieldSetElement_Native
 * Method:    get_form
 * Signature: (J)Ljp/hishidama/win32/mshtml/IHTMLFormElement;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFieldSetElement_00024Native_get_1form
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
