/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_shdocvw_IWebBrowser_Native */

#ifndef _Included_jp_hishidama_win32_shdocvw_IWebBrowser_Native
#define _Included_jp_hishidama_win32_shdocvw_IWebBrowser_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_create
  (JNIEnv *, jclass);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    enumWebBrowser
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_enumWebBrowser
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    findWebBrowser
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_findWebBrowser
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    GoBack
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_GoBack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    GoForward
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_GoForward
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    GoHome
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_GoHome
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    GoSearch
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_GoSearch
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    Navigate
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_Navigate
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    Refresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_Refresh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    Stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_Stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Document
 * Signature: (J)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Document
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Type
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Left
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Left
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_Left
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1Left
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Top
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Top
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_Top
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1Top
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_Width
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1Width
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Height
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_Height
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1Height
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_LocationName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1LocationName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_LocationURL
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1LocationURL
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Busy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Busy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    Quit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_Quit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_HWND
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1HWND
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_FullName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1FullName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Path
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Path
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Visible
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Visible
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_Visible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1Visible
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_StatusBar
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1StatusBar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_StatusBar
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1StatusBar
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_StatusText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1StatusText
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_StatusText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1StatusText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_ToolBar
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1ToolBar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_ToolBar
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1ToolBar
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_MenuBar
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1MenuBar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_MenuBar
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1MenuBar
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_FullScreen
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1FullScreen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_FullScreen
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1FullScreen
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_ReadyState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1ReadyState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Offline
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Offline
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_Offline
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1Offline
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Silent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Silent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_Silent
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1Silent
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_RegisterAsBrowser
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1RegisterAsBrowser
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_RegisterAsBrowser
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1RegisterAsBrowser
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_RegisterAsDropTarget
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1RegisterAsDropTarget
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_RegisterAsDropTarget
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1RegisterAsDropTarget
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_TheaterMode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1TheaterMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_TheaterMode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1TheaterMode
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_AddressBar
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1AddressBar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_AddressBar
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1AddressBar
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    get_Resizable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_get_1Resizable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_shdocvw_IWebBrowser_Native
 * Method:    put_Resizable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_shdocvw_IWebBrowser_00024Native_put_1Resizable
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
