/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLBaseElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLBaseElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLBaseElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLBaseElement_Native
 * Method:    put_href
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLBaseElement_00024Native_put_1href
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLBaseElement_Native
 * Method:    get_href
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLBaseElement_00024Native_get_1href
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLBaseElement_Native
 * Method:    put_target
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLBaseElement_00024Native_put_1target
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLBaseElement_Native
 * Method:    get_target
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLBaseElement_00024Native_get_1target
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
