/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLHRElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLHRElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLHRElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    put_align
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_put_1align
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    get_align
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_get_1align
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    put_color
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_put_1color
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    get_color
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_get_1color
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    put_noShade
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_put_1noShade
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    get_noShade
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_get_1noShade
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    put_width
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_put_1width
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    get_width
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_get_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    put_size
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_put_1size
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHRElement_Native
 * Method:    get_size
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHRElement_00024Native_get_1size
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
