/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLFrameElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLFrameElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLFrameElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFrameElement_Native
 * Method:    put_borderColor
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFrameElement_00024Native_put_1borderColor
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFrameElement_Native
 * Method:    get_borderColor
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFrameElement_00024Native_get_1borderColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFrameElement_Native
 * Method:    put_height
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFrameElement_00024Native_put_1height
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFrameElement_Native
 * Method:    get_height
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFrameElement_00024Native_get_1height
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFrameElement_Native
 * Method:    put_width
 * Signature: (JLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFrameElement_00024Native_put_1width
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLFrameElement_Native
 * Method:    get_width
 * Signature: (J)Ljp/hishidama/win32/com/Variant;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLFrameElement_00024Native_get_1width
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
