/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLAreaElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_shape
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1shape
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_shape
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1shape
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_coords
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1coords
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_coords
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1coords
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_href
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1href
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_href
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1href
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_target
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1target
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_target
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1target
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_alt
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1alt
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_alt
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1alt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_noHref
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1noHref
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_noHref
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1noHref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_host
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1host
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_host
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1host
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_hostname
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1hostname
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_hostname
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1hostname
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_pathname
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1pathname
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_pathname
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1pathname
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_port
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1port
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_port
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1port
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_protocol
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1protocol
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_protocol
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1protocol
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_search
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1search
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_search
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1search
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_hash
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1hash
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_hash
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1hash
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    put_tabIndex
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_put_1tabIndex
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    get_tabIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_get_1tabIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    focus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_focus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreaElement_Native
 * Method:    blur
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreaElement_00024Native_blur
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
