/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLHeadElement_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLHeadElement_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLHeadElement_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHeadElement_Native
 * Method:    put_profile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHeadElement_00024Native_put_1profile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLHeadElement_Native
 * Method:    get_profile
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_hishidama_win32_mshtml_IHTMLHeadElement_00024Native_get_1profile
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
