/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native */

#ifndef _Included_jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
#define _Included_jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
 * Method:    put_length
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreasCollection_00024Native_put_1length
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
 * Method:    get_length
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreasCollection_00024Native_get_1length
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
 * Method:    get__newEnum
 * Signature: (J)Ljp/hishidama/win32/com/IUnknown;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreasCollection_00024Native_get_1_1newEnum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
 * Method:    item
 * Signature: (JLjp/hishidama/win32/com/Variant;Ljp/hishidama/win32/com/Variant;)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreasCollection_00024Native_item
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
 * Method:    tags
 * Signature: (JLjp/hishidama/win32/com/Variant;)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreasCollection_00024Native_tags
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
 * Method:    add
 * Signature: (JJLjp/hishidama/win32/com/Variant;)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreasCollection_00024Native_add
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
 * Method:    remove
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreasCollection_00024Native_remove
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
 * Method:    urns
 * Signature: (JLjp/hishidama/win32/com/Variant;)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreasCollection_00024Native_urns
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     jp_hishidama_win32_mshtml_IHTMLAreasCollection_Native
 * Method:    namedItem
 * Signature: (JLjava/lang/String;)Ljp/hishidama/win32/com/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_jp_hishidama_win32_mshtml_IHTMLAreasCollection_00024Native_namedItem
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
